# Generated by Django 6.0.3 on 2026-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_profile_certifications_profile_projects_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certifications',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects_completed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
