# Generated by Django 6.0.3 on 2026-03-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_contact_github_name_contact_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('design', 'Design')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
