# Generated by Django 6.0.3 on 2026-03-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_skill_category_alter_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approach',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
