# Generated by Django 6.0.3 on 2026-05-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
