# Generated by Django 6.0.3 on 2026-05-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_remove_profile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='display_type',
            field=models.CharField(choices=[('title', 'Title'), ('bullet', 'Bullet'), ('plain', 'Plain')], default='bullet', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='heading',
            field=models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], default='h3', max_length=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myApp.skill'),
        ),
    ]
