# Generated by Django 6.0.3 on 2026-05-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_remove_skill_category_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skills'), ('other', 'Other Skills')], default='technical', max_length=20),
        ),
    ]
