# Generated by Django 6.0.3 on 2026-05-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='display_type',
            field=models.CharField(choices=[('title', 'Bold'), ('bullet', 'Bullet'), ('plain', 'Plain')], default='bullet', max_length=20),
        ),
    ]
