# Generated by Django 6.0.3 on 2026-05-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='place_obtained',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
