# Generated by Django 6.0.3 on 2026-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='show_icon',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='heading',
            field=models.CharField(choices=[('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4'), ('h5', 'H5'), ('h6', 'H6')], default='h3', max_length=2),
        ),
    ]
