# Generated by Django 6.0.3 on 2026-09-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_skill_icon_skill_show_icon_alter_skill_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
