# Generated by Django 6.0.3 on 2026-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0024_skill_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='what_i_learned',
            field=models.TextField(blank=True),
        ),
    ]
