# Generated by Django 6.0.3 on 2026-09-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_preview',
            field=models.ImageField(blank=True, null=True, upload_to='resume_previews/'),
        ),
    ]
