# Generated by Django 6.0.3 on 2026-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_profile_resume_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech',
            field=models.TextField(blank=True),
        ),
    ]
